AWSTemplateFormatVersion: '2010-09-09'
Description: 'T4 GPU Development Environment for ML Tasks (Ubuntu)'

Parameters:
  MyIpAddress:
    Description: IP address to allow SSH access (CIDR format, e.g., 1.2.3.4/32)
    Type: String
    Default: '0.0.0.0/0'

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 KeyPair

  InstanceType:
    Description: Instance type with Tesla T4 GPU
    Type: String
    Default: g4dn.xlarge
    AllowedValues:
      - g4dn.xlarge    # 1 GPU, 4 vCPU, 16 GB
      - g4dn.2xlarge   # 1 GPU, 8 vCPU, 32 GB
      - g4dn.4xlarge   # 1 GPU, 16 vCPU, 64 GB

  VolumeSize:
    Description: Size of the root volume in GB
    Type: Number
    Default: 100
    MinValue: 8

Mappings:
  # Deep Learning AMIs with CUDA pre-installed (Ubuntu)
  RegionMap:
    us-east-1:
      AMI: ami-0c078c0b25ad46e40  # Keep this ID since it's what your instance is using

Resources:
  # Security Group for T4 Instance
  GPUInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for T4 GPU instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIpAddress
          Description: SSH access from my IP
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-security-group

  # IAM Role for EC2 instance
  GPUInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: ParameterStoreAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:GetParametersByPath
                Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/unsloth-tasks/*
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-instance-role

  # Instance Profile for the IAM Role
  GPUInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref GPUInstanceRole

  # T4 GPU Instance
  GPUInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !GetAtt GPUInstanceSecurityGroup.GroupId
      IamInstanceProfile: !Ref GPUInstanceProfile
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: !Ref VolumeSize
            VolumeType: gp3
            DeleteOnTermination: true
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1

          sudo -u ubuntu git clone https://github.com/nicktalati/unsloth-tasks.git /home/ubuntu/unsloth-tasks

          curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
          rm -rf /opt/nvim
          tar -C /opt -xzf nvim-linux-x86_64.tar.gz

          echo 'export PATH="$PATH:/opt/nvim-linux-x86_64/bin"' >> /home/ubuntu/.bashrc

          sudo -u ubuntu cat > /home/ubuntu/.inputrc << 'EOL'
          set editing-mode vi
          set keymap vi-insert
          "kj": "\e"
          EOL

          sudo -u ubuntu mkdir -p /home/ubuntu/.config/nvim
          sudo -u ubuntu git clone https://github.com/nicktalati/nvim-config.git /home/ubuntu/nvim-config
          sudo -u ubuntu cp /home/ubuntu/nvim-config/init.lua /home/ubuntu/.config/nvim/
          chown -R ubuntu:ubuntu /home/ubuntu/.config

          cat > /home/ubuntu/welcome.txt << 'EOL'

          ==========================================================
            Welcome to your T4 GPU Development Environment!
          ==========================================================

          Happy coding!
          EOL

          echo "cat /home/ubuntu/welcome.txt" >> /home/ubuntu/.bashrc
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-t4-instance
        - Key: AutoShutdown
          Value: 'true'

  LowCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Shutdown instance after extended idle time
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 3600  # 1 hour
      EvaluationPeriods: 2
      Threshold: 10  # 10% CPU
      ComparisonOperator: LessThanThreshold
      Dimensions:
        - Name: InstanceId
          Value: !Ref GPUInstance
      AlarmActions:
        - !Sub arn:aws:automate:${AWS::Region}:ec2:stop

Outputs:
  InstanceId:
    Description: ID of the T4 GPU instance
    Value: !Ref GPUInstance

  PublicIP:
    Description: Public IP address of the T4 GPU instance
    Value: !GetAtt GPUInstance.PublicIp

  SSHCommand:
    Description: Command to SSH into the instance
    Value: !Sub ssh -i ${KeyName}.pem ubuntu@${GPUInstance.PublicIp}
